;;; (html? v) -> boolean?
;;;  v : any
;;; Returns `#t` if and only if `v` is an HTML element.
(define html? (js-var "html_isElement"))

;;; (subscription? v) -> boolean?
;;;  v : any
;;; Returns `#t` if and only if `v` is a subscription.
(define subscription? (js-var "reactive_subscriptionQ"))

;;; (reactive-canvas width height initial view update sub1) -> html?
;;;  width : number?
;;;  height : number?
;;;  initial : any
;;;  view : any
;;;   function? takes a state and canvas as input and renders that state to the canvas.
;;;  update : any
;;;   function? takes a message and state as input and returns a new state as output.
;;;  sub1 : subscription?
;;; Creates a reactive canvas with the given width and height. The canvas renders as model with the given `initial` value and `view` function. The `update` function handles all messages generated by the given subscriptions.
;;; @category reactive, canvas
(define reactive-canvas (js-var "reactive_reactiveCanvas"))

;;; (reactive-container initial view update sub1) -> html?
;;;  initial : any
;;;  view : any
;;;   function? takes a state as input and outputs an HTML element as output.
;;;  update : any
;;;   function? takes a message and state as input and returns a new state as output.
;;;  sub1 : subscription?
;;; Creates a reactive HTML container. The canvas renders as model with the given `initial` value and `view` function. The `view` function outputs an HTML tree that the container displays. The `update` function handles all messages generated by the given subscriptions.
;;; @category reactive
(define reactive-container (js-var "reactive_reactiveContainer"))

;;; (on-button-click button) -> subscription?
;;;  button : button?
;;; Returns a subscription that emits a message of the form `(event-button-click id)` whenever the given button is clicked. The `id` is the given button's id or `void` is no `id` assigned to the button.
;;; @category reactive
(define on-button-click (js-var "reactive_onButtonClick"))

;;; (on-mouse-click) -> subscription?
;;; Returns a subscription that emits a message of the form `(event-mouse-click button x y)` whenever the canvas is clicked. `button` indicates which mouse button was clicked and `(x, y)` are the coordinates where the click occurred.
;;; @category reactive
(define on-mouse-click (js-var "reactive_onMouseClick"))

;;; (on-mouse-hover) -> subscription?
;;; Returns a subscription that emits a message of the form `(event-mouse-hover x y)` whenever the mouse moves over the reactive element. `(x, y)` are the coordinates of the mouse.
;;; @category reactive
(define on-mouse-hover (js-var "reactive_onMouseHover"))

;;; (on-key-down) -> subscription?
;;; Returns a subscription that emits a message of the form `(event-key-down key)` whenever a key is pressed. `key` indicates the key that was pressed.
;;; @category reactive
(define on-key-down (js-var "reactive_onKeyDown"))

;;; (on-key-up) -> subscription?
;;; Returns a subscription that emits a message of the form `(event-key-up key)` whenever a key is released. `key` indicates the key that was released.
;;; @category reactive
(define on-key-up (js-var "reactive_onKeyUp"))

;;; (on-timer interval) -> subscription?
;;;  interval : any
;;;   non-negative integer
;;; Returns a subscription that emits a message of the form `(event-timer time elapsed)` every `interval` milliseconds. `time` is the current time since the page was loaded and `elapsed` is the time since the last timer message, all in milliseconds.
;;; @category reactive
(define on-timer (js-var "reactive_onTimer"))

;;; (on-note handlers) -> subscription?
;;;  handlers : vector?
;;; Returns a subscription that emits a message of the form `(event-note id)` whenever `(note-event id)` is played in a composition that users `handlers` to handle events.
;;; @category reactive
(define on-note (js-var "reactive_onNote"))
