#!/usr/bin/env bash

SERVER=compsci
ROOT=scamper.cs.grinnell.edu
VER=$1

echo "Deploying ${VER}"

tsc
vite build --base=/${VER}/
rsync -crtvz --progress dist/ ${SERVER}:${ROOT}/${VER}

cat << EOF | ssh ${SERVER} "cat > ${ROOT}/index.html"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="refresh" content="0; url=${VER}/">
  <title>Redirecting to latest Scamper version...</title>
</head>
<body>
  <p>If you are not redirected automatically, follow this <a href="${VER}/">link to Scamper ${VER}</a>.</p>
</body>
</html></html>
EOF 