


export const builtinLibs = new Map<string, string[]>([
    ["list", ["append", "apply", "assoc-key ?", "assoc-ref", "assoc-set", "car", "cdr", "cons", "c...r", "filter", "fold", "fold-left", 
            "fold-right", "index-of", "length", "list", "list-drop", "list-of", "list?", "list-ref", "list->string", "list-tail", 
            "list-take", "list->vector", "make-list", "map", "null?", "null", "pair", "range", "reduce", "reduce-right", "reverse",
            "sort", "string -> list", "tally-all", "vector -> list"]] ,
    ["list manipulation", ["append", "apply", "assoc-key?", "assoc-ref", "assoc-set", "car", "cdr", "c...r", "filter", "fold", "fold-left",
            "fold-right", "index-of", "length", "list-drop", "list->string", "list-tail", "list-take", "list->vector", "map", 
            "reduce", "reduce-right", "reverse", "sort"]],
    ["list creation", ["cons", "list", "make-list", "null", "pair", "range", "string->list", "vector->list"]],
    ["math", ["abs", "acos", "asin", "atan", "ceiling", "cos", "/", "even?", "exp", "expt", "floor", ">=", ">", "integer?", "<=", "log",
            "<", "max", "min", "-", "modulo", "nan?", "negative?", "number?", "=", "odd?", "pi", "π", "+", "positive?", "quotient", "real?", 
            "remainder", "round", "sin", "sqrt", "square", "tan", "*", "truncate", "zero?"]],
    ["algebra", ["abs", "ceiling", "/", "exp", "expt", "floor", "log", "-", "modulo", "pi", "π", "+", "quotient",
            "remainder", "round", "sqrt", "square", "*", "truncate"]],
    ["comparator", ["even?", ">=", ">", "integer?", "<=", "<", "max", "min", "nan?", "negative?", "number?", "=", "odd?", "positive?",
            "real?", "zero?"]],
    ["trigonometry", ["acos", "asin", "atan", "cos", "sin", "tan"]],
    ["function composition", ["all-of", "any-of", "compose", "=-eps", "list-of", "o", "|>]"]],
    ["association list", ["assoc-key?", "assoc-ref", "assoc-set", "car", "cdr", "cons", "c...r", "filter", "fold",
            "fold-left", "fold-right", "index-of", "list", "list-drop", "list-of", "list?", "list-ref", "list->string",
            "list-tail", "list-take", "list->vector", "make-list", "map", "null?", "null", "sort"]],
    ["type check", ["boolean?", "char-alphabetic?", "char-numeric?", "char?", "char-upper-case?", "char-whitespace?", "digit-value",
            "integer?", "ref?", "list?", "nan?", "negative?", "null?", "number?", "odd?", "pair?", "positive?", "procedure?",
            "real?", "string?", "vector?", "void?", "zero?", "color?", "image?", "color-name?", "hsv?", "rgb?", "rgb-component?", "shape?",
            "composition?", "dur?", "mod?", "note-value?", "octave?", "pitch?", "dataset?", "plot?", "rex-matches?", "rex?"]],
    ["string", ["error", "file->lines", "file->string", "make-string", "number->string", "string", "string-append", "string-contains",
            "string-downcase", "string=?", "string-ci=?", "string-foldcase", "string>=?", "string-ci>=?", "string>?", "string-ci>?", 
            "string-length", "string<=?", "string-ci<=?", "string->list", "string<?", "string-ci<?", "string-map", "string->number", "string?",
            "string-ref", "string-split", "string-split-vector", "string->words", "string-upcase", "string->vector", "substring",
            "string->chars", "string->lines", "string->words"]],
    ["boolean/logic", ["all-of", "any-of", "boolean?", "else", "implies", "nand", "nor", "not", "xor"]],
    ["char", ["char-alphabetic?", "char-downcase", "char=?", "char-ci=?", "char-foldcase", "char>=?", "char-ci>=?", "char>?",
            "char-ci>?", "char<=?", "char-ci<=?", "char-lower-case?", "char<?", "char-ci<?", "char-numeric?", "char?", "char->integer",
            "char-upcase", "char-upper-case?", "char-whitespace?", "digit-value", "integer->char", "string->chars"]],
    ["regexes", ["rex-any-char", "rex-any-of", "rex-char-antiset", "rex-char-range", "rex-char-set", "rex-concat", "rex-empty",
            "rex-find-matches", "rex-matches?", "rex-optional", "rex?", "regex", "rex-repeat", "rex-repeat-0", "rex-split-string",
            "rex-string", "rex->string"]],
    ["vectors", ["list->vector", "make-vector", "string-split-vector", "string->vector", "vector", "vector-append",
            "vector-fill!", "vector-filter", "vector-for-each", "vector-length", "vector->list", "vector-map", "vector-map!",
            "vector?", "vector-range", "vector-ref", "vector-set!", "vector->string"]],
["mutation", ["set-maximum-recursion-depth!", "set-ref!", "vector-fill!", "vector-map!", "vector-set!", "canvas-set-pixels!",
            "canvas-circle!", "canvas-drawing!", "canvas-ellipse!", "canvas-onclick!", "canvas-path!", "canvas-rectangle!",
            "canvas-text!", "on-keydown!", "tag-set-children!"]],
    ["predicates", ["assoc-key?", "boolean?", "char-alphabetic?", "char=?", "char-ci=?", "char>=?", "char-ci>=?", "char>?",
            "char-ci>?", "char<=?", "char-ci<=?", "char-lower-case?", "char<?", "char-ci<?", "char-numeric?", "char?", "char-upper-case?", 
            "char-whitespace?", "equal?", "even?", "implies", "integer?", "ref?", "list?", "nan?", "negative?", "null?", "number?", 
            "odd?", "pair?", "positive?", "procedure?", "real?", "set-maximum-recursion-depth!", "set-ref!", "string=?", "string-ci=?",
            "string>=?", "string-ci>=?", "string>?", "string-ci>?", "string<=?", "string-ci<=?", "string<?", "string-ci<?", "string?",
            "vector-fill!", "vector-map!", "vector?", "vector-set!", "void?", "zero?", "canvas-set-pixels!", "color?", "image?",
            "color-name?", "hsv?", "rgb?", "rgb-component?", "shape?", "composition?", "dur?", "mod?", "note-value?", "octave?",
            "pitch?", "canvas-circle!", "canvas-drawing!", "canvas-ellipse!", "canvas-onclick!", "canvas-path!", "canvas-rectangle!",
            "canvas-text!", "on-keydown!", "tag-set-children!", "dataset?", "plot?", "rex-matches?", "rex?"]],
    ["testing", ["error", "test-case", "test-error", "test-exn", "test-ok"]],
    ["formatting", ["description", "part", "problem", "title"]],
    ["constants", ["else", "null", "pi", "π", "??", "void", "all-color-names", "empty", "en", "hn", "percussion",
            "qn", "sn", "trigger", "wn"]]
  ])