#!/usr/bin/env bash

VER=$(npm pkg get version | tr -d '"')

echo "Building from $(pwd)"

if [[ -n "$1" ]] && [[ "${1}" == "clean" ]]; then
  echo "Cleaning site..."
  rm -rf site/ src/version.ts
fi

mkdir -p site/

echo "Building Javascript..."
npm run build

echo "Building documents..."
make -C docs
cp -r docs/dist/docs site

echo "Copying media and web support..."
cp -r ide/webfonts ide/css ide/images site

filter_page() {
  sed s/{{ver}}/${VER}/g ide/$1 > site/$2
}

echo "Generating webpages..."
filter_page "file-chooser.html" "index.html"
filter_page "file-chooser.html" "file-chooser-${VER}.html"
filter_page "ide.html" "ide-${VER}.html"
filter_page "runner.html" "runner-${VER}.html"
filter_page "reference.html" "reference.html"
