import * as L from './lang.js'
import { ICE } from './error.js'
import { Range } from './range.js'

/**
 * A stack frame records all relevant to track the execution of a single function call.
 */
export class Frame {
  name: string
  env: L.Env
  values: L.Value[]
  ops: L.Ops[]
  // N.B., the range of the Ap that invoked this frame's closure -- i.e.
  // where, in the *caller's* source, this call textually appears. Used to
  // recover a meaningful range for errors raised deep inside a contract
  // wrapper's own generated bytecode (whose ops carry the wrapped
  // definition's range, not any real call site). Range.none for the
  // synthetic per-statement frame beginProcessingBlk creates, which has no
  // caller of its own.
  callRange: Range

  constructor(name: string, env: L.Env, blk: L.Blk, callRange: Range = Range.none) {
    this.name = name
    this.env = env
    this.values = []
    this.ops = blk.toReversed()
    this.callRange = callRange
  }

  isFinished(): boolean {
    return this.ops.length === 0
  }

  /**
   * True when nothing remains to run except `pop-scope` bookkeeping. Those
   * scopes belong to this frame, which a tail call is about to discard, so it
   * is safe to replace the frame (preserving tail-call optimization through
   * `let`/`match` bodies) rather than push a new one.
   */
  canTailCall(): boolean {
    return this.ops.every((op) => op.tag === 'pop-scope')
  }

  pushBlk(blk: L.Blk) {
    this.ops.push(...blk.toReversed())
  }

  popInstr(): L.Ops {
    const op = this.ops.pop()
    if (!op)
      throw new ICE(
        'Frame.popInstr',
        `Attempted to pop operation off frame ${this.name} when none remain`,
      )
    return op
  }
}
