import * as L from "./lang.js"
import { ICE } from "./error.js"
import { Range } from "./range.js"

/**
 * A stack frame records all relevant to track the execution of a single function call.
 */
export class Frame {
  name: string
  env: L.Env
  values: L.Value[]
  ops: L.Ops[]
  // N.B., the range of the Ap that invoked this frame's closure -- i.e.
  // where, in the *caller's* source, this call textually appears. Used to
  // recover a meaningful range for errors raised deep inside a contract
  // wrapper's own generated bytecode (whose ops carry the wrapped
  // definition's range, not any real call site). Range.none for the
  // synthetic per-statement frame beginProcessingBlk creates, which has no
  // caller of its own.
  callRange: Range
  // N.B., true only for a frame executing a contract.ts-generated wrapper
  // (see ast.ts's Lam.isContractWrapper). This, not the frame's name, is
  // what actually licenses preferring callRange/name over an op's own
  // range/a raw JS function's name -- a wrapper's entire body is a
  // check-then-call whose ops all carry the wrapped definition's range, so
  // "blame whoever called this frame" is always right. An ordinary named
  // function (isContractWrapper false) does NOT get this treatment: its own
  // ops already carry correct, distinct ranges for whatever they call, at
  // whatever depth, and callRange only ever points at its *own* call site.
  isWrapperFrame: boolean

  constructor(
    name: string,
    env: L.Env,
    blk: L.Blk,
    callRange: Range = Range.none,
    isWrapperFrame = false,
  ) {
    this.name = name
    this.env = env
    this.values = []
    this.ops = blk.toReversed()
    this.callRange = callRange
    this.isWrapperFrame = isWrapperFrame
  }

  isFinished(): boolean {
    return this.ops.length === 0
  }

  pushBlk(blk: L.Blk) {
    this.ops.push(...blk.toReversed())
  }

  popInstr(): L.Ops {
    const op = this.ops.pop()
    if (!op)
      throw new ICE(
        "Frame.popInstr",
        `Attempted to pop operation off frame ${this.name} when none remain`,
      )
    return op
  }
}
