import * as L from './lang.js'
import { ICE } from './error.js'
import { Range } from './range.js'

/**
 * A stack frame records all relevant to track the execution of a single function call.
 */
export class Frame {
  name: string
  env: L.Env
  values: L.Value[]
  ops: L.Ops[]
  // N.B., the range of the Ap that invoked this frame's closure -- i.e.
  // where, in the *caller's* source, this call textually appears. Used to
  // recover a meaningful range for errors raised deep inside a contract
  // wrapper's own generated bytecode (whose ops carry the wrapped
  // definition's range, not any real call site). Range.none for the
  // synthetic per-statement frame beginProcessingBlk creates, which has no
  // caller of its own.
  callRange: Range
  // Where this frame's code came from (see L.CodeOrigin). Propagated from the
  // applied closure, so the tracer can keep a library/import call atomic and
  // library code can skip the contract checks of the functions it names.
  // 'user' for the synthetic per-statement frame and the student's own
  // closures.
  origin: L.CodeOrigin
  // The applied closure's `home` env, if any (see Closure.home). Propagated so
  // that a lambda created while this frame runs inherits the same home -- a
  // closure returned by a qualified-module function must still resolve the
  // module's siblings. Undefined for ordinary frames (dynamic fiber resolution).
  home?: L.Env
  // A reduction trace must not surface this frame's steps. Normally that is
  // just "not the student's code", but a tail call *replaces* its caller's
  // frame, so a replacement inherits a hidden caller's shield (see
  // Fiber.replaceFrame) -- otherwise a library function tail-calling a closure
  // spills the rest of that call into the trace (#478). Visibility only:
  // `origin` still says whose code this frame runs, which is what decides
  // contract checks and error ranges.
  hidden: boolean

  constructor(
    name: string,
    env: L.Env,
    blk: L.Blk,
    callRange: Range = Range.none,
    origin: L.CodeOrigin = 'user',
    home?: L.Env,
  ) {
    this.name = name
    this.env = env
    this.values = []
    this.ops = blk.toReversed()
    this.callRange = callRange
    this.origin = origin
    this.home = home
    this.hidden = origin !== 'user'
  }

  isFinished(): boolean {
    return this.ops.length === 0
  }

  /**
   * True when nothing remains to run except `pop-scope` bookkeeping. Those
   * scopes belong to this frame, which a tail call is about to discard, so it
   * is safe to replace the frame (preserving tail-call optimization through
   * `let`/`match` bodies) rather than push a new one.
   */
  canTailCall(): boolean {
    return this.ops.every((op) => op.tag === 'pop-scope')
  }

  pushBlk(blk: L.Blk) {
    this.ops.push(...blk.toReversed())
  }

  popInstr(): L.Ops {
    const op = this.ops.pop()
    if (!op)
      throw new ICE(
        'Frame.popInstr',
        `Attempted to pop operation off frame ${this.name} when none remain`,
      )
    return op
  }
}
